apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://9CE1397CC60B3355E65F3D262D9D1C26.gr7.ap-south-1.eks.amazonaws.com
  name: arn:aws:eks:ap-south-1:756999892440:cluster/traffic-hotspots-cluster
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://165D3618963915019E4AF7AE705BF32A.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:756999892440:cluster/aws-glue-eks
contexts:
- context:
    cluster: arn:aws:eks:ap-south-1:756999892440:cluster/traffic-hotspots-cluster
    user: arn:aws:eks:ap-south-1:756999892440:cluster/traffic-hotspots-cluster
  name: arn:aws:eks:ap-south-1:756999892440:cluster/traffic-hotspots-cluster
- context:
    cluster: arn:aws:eks:us-east-1:756999892440:cluster/aws-glue-eks
    user: arn:aws:eks:us-east-1:756999892440:cluster/aws-glue-eks
  name: arn:aws:eks:us-east-1:756999892440:cluster/aws-glue-eks
current-context: arn:aws:eks:us-east-1:756999892440:cluster/aws-glue-eks
kind: Config
preferences: {}
users:
- name: arn:aws:eks:ap-south-1:756999892440:cluster/traffic-hotspots-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - ap-south-1
      - eks
      - get-token
      - --cluster-name
      - traffic-hotspots-cluster
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: arn:aws:eks:us-east-1:756999892440:cluster/aws-glue-eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - aws-glue-eks
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false